#**MERGE**

In [ ]:
# Import the pandas library for data manipulation
import pandas as pd

# Create the first DataFrame (df1)
df1 = pd.DataFrame({"A" : [2,3,4,5], "B" : ["a","b","c","d"]})

# Create the second DataFrame (df2)
df2 = pd.DataFrame({"A" : [2,4,6,8], "B" : ["a", "c", "e", "f"]})

# Perform a merge operation on df1 and df2.
pd.merge(df1, df2)

   A  B
0  2  a
1  4  c

In [ ]:
# Import the pandas library for data manipulation
import pandas as pd

# Create the first DataFrame (df1)
df1 = pd.DataFrame({"A" : [2,3,4,5], "B" : ["a","b","c","d"]})

# Create the second DataFrame (df2) with a different column 'C'
df2 = pd.DataFrame({"A" : [2,4,6,8], "C" : ["a", "c", "e", "f"]})

# Perform a merge operation on df1 and df2.
pd.merge(df1, df2)

   A  B  C
0  2  a  a
1  4  c  c

In [ ]:
import pandas as pd

#Create the dataframes
df1 = pd.DataFrame({"A" : [2,3,4,5], "B" : ["a","b","c","d"]})
df2 = pd.DataFrame({"A" : [2,4,6,8], "B" : ["a", "c", "e", "f"]})

#Merge both dataframes using the common column
pd.merge(df1, df2)

#Perform an explicit inner join using column A
pd.merge(df1, df2 ,on= "A",how="inner")

   A B_x B_y
0  2   a   a
1  4   c   c

In [ ]:
import pandas as pd

#Create the dataframes
df1 = pd.DataFrame({"A" : [2,3,4,5], "B" : ["a","b","c","d"]})
df2 = pd.DataFrame({"A" : [2,4,6,8], "B" : ["a", "c", "e", "f"]})

#Merge both dataframes using the common column
pd.merge(df1, df2)

#Perform an explicit left join using column A
pd.merge(df1, df2 ,on= "A",how="left")

   A B_x  B_y
0  2   a    a
1  3   b  NaN
2  4   c    c
3  5   d  NaN

In [ ]:
import pandas as pd

#Create the dataframes
df1 = pd.DataFrame({"A" : [2,3,4,5], "B" : ["a","b","c","d"]})
df2 = pd.DataFrame({"A" : [2,4,6,8], "B" : ["a", "c", "e", "f"]})

#Merge both dataframes using the common column
pd.merge(df1, df2)

#Perform an explicit inner join using column A
pd.merge(df1, df2 ,on= "A",how="outer")

   A  B_x  B_y
0  2    a    a
1  3    b  NaN
2  4    c    c
3  5    d  NaN
4  6  NaN    e
5  8  NaN    f

In [ ]:
import pandas as pd

#Create the dataframes
df1 = pd.DataFrame({"A" : [2,3,4,5], "B" : ["a","b","c","d"]})
df2 = pd.DataFrame({"A" : [2,3,4,5], "B" : ["a", "c", "e", "f"]})


#Merge both dataframes using the common column
pd.merge(df1, df2)

   A  B
0  2  a

In [ ]:
import pandas as pd

#Create the dataframes
df1 = pd.DataFrame({"A" : [1,2,3,4], "B" : ["a", "b", "c", "d"]})
df2 = pd.DataFrame({"A" : [1,2,3,4], "B" : ["e","f","g","h"]})

#Merge both dataframes using the common column
pd.merge(df1, df2)

Empty DataFrame
Columns: [A, B]
Index: []

In [ ]:
import pandas as pd

#Create the dataframes
df1 = pd.DataFrame({"A" : [2,3,4,5], "A" : ["a","b","c","d"]})
df2 = pd.DataFrame({"A" : [2,3,4,5], "A" : ["a", "c", "e","f"]})

#Merge both dataframes using the common column
pd.merge(df1, df2)

   A
0  a
1  c

In [ ]:
import pandas as pd

#Create the dataframes
df1 = pd.DataFrame({"A" : [2,3,4,5], "A" : ["a","b","c","d"]})
df2 = pd.DataFrame({"A" : [2,3,4,5], "A" : ["a", "c", "e","f"]})

#Only matching values are included by deffault (inner merge)
pd.merge(df1, df2, on = "A")

   A
0  a
1  c

In [ ]:
import pandas as pd

#Create the first data frame containing roll number and name
v1 = pd.DataFrame({"rollno" : [20,21,22], "name" : ["a",'b',"c"]})

#Create the first data frame containing roll number and marks
v2 = pd.DataFrame({"rollno" : [20,21,22], "marks" : [60,20,80]})

#Merge both dataframes using the common column
s = pd.merge(v1,v2)

print(s)

   rollno name  marks
0      20    a     60
1      21    b     20
2      22    c     80

In [ ]:
import pandas as pd
v1 = pd.DataFrame({"rollno" : [20,21,22,23,24], "name" : ["kanishka",'umang',"naina","kunal","manu"]})
v2 = pd.DataFrame({"rollno" : [20,21,22,23,24], "marks" : [60,20,80,50,70]})
s = pd.merge(v1,v2)
print(s)

   rollno      name  marks
0      20  kanishka     60
1      21     umang     20
2      22     naina     80
3      23     kunal     50
4      24      manu     70

In [ ]:
import pandas as pd
v1 = pd.DataFrame({"rollno" : [20,21,22,30,24], "name" : ["kanishka",'umang',"naina","kunal","manu"]})
v2 = pd.DataFrame({"rollno" : [20,21,22,23,25], "marks" : [60,20,80,50,70]})
std_info = pd.merge(v1,v2, how = "left")
print(std_info)

   rollno      name  marks
0      20  kanishka   60.0
1      21     umang   20.0
2      22     naina   80.0
3      30     kunal    NaN
4      24      manu    NaN

In [ ]:
import pandas as pd
v1 = pd.DataFrame({"rollno" : [20,21,22,30,24], "name" : ["kanishka",'umang',"naina","kunal","manu"]})
v2 = pd.DataFrame({"rollno" : [20,21,22,23,25], "marks" : [60,20,80,50,70]})
std_info = pd.merge(v1,v2, how = "inner")
print(std_info)

   rollno      name  marks
0      20  kanishka     60
1      21     umang     20
2      22     naina     80

In [ ]:
import pandas as pd
v1 = pd.DataFrame({"rollno" : [20,21,22,30,24], "name" : ["kanishka",'umang',"naina","kunal","manu"]})
v2 = pd.DataFrame({"rollno" : [20,21,22,23,25], "marks" : [60,20,80,50,70]})
std_info = pd.merge(v1,v2, how = "outer")
print(std_info)

   rollno      name  marks
0      20  kanishka   60.0
1      21     umang   20.0
2      22     naina   80.0
3      23       NaN   50.0
4      24      manu    NaN
5      25       NaN   70.0
6      30     kunal    NaN

In [ ]:
import pandas as pd
v1 = pd.DataFrame({"rollno" : [20,21,22,30,24], "name" : ["kanishka",'umang',"naina","kunal","manu"]})
v2 = pd.DataFrame({"rollno" : [20,21,22,23,25], "marks" : [60,20,80,50,70]})
std_info = pd.merge(v1,v2, how = "right")
print(std_info)

   rollno      name  marks
0      20  kanishka     60
1      21     umang     20
2      22     naina     80
3      23       NaN     50
4      25       NaN     70

In [ ]:
import pandas as pd
v1 = pd.DataFrame({"rollno" : [20,21,22,30,24], "name" : ["kanishka",'umang',"naina","kunal","manu"]})
v2 = pd.DataFrame({"rollno" : [20,21,22,23,25], "marks" : [60,20,80,50,70]})
std_info = pd.merge(v1,v2, how = "outer", indicator = "True")
print(std_info)

   rollno      name        True
0      20  kanishka        both
1      21     umang        both
2      22     cheya  right_only
3      22     naina   left_only
4      23     kunal  right_only
5      24      manu   left_only
6      25    anjali  right_only
7      30     kunal   left_only

In [ ]:
import pandas as pd
v1 = pd.DataFrame({"rollno" : [20,21,22,30,24], "name" : ["kanishka",'umang',"naina","kunal","manu"]})
v2 = pd.DataFrame({"rollno" : [20,21,22,23,25], "name" : ["kanishka",'umang',"anjali","kunal","shipra"]})
std_info = pd.merge(v1,v2, how = "outer")
print(std_info)

   rollno      name
0      20  kanishka
1      21     umang
2      22    anjali
3      22     naina
4      23     kunal
5      24      manu
6      25    shipra
7      30     kunal

In [ ]:
import pandas as pd
v1 = pd.DataFrame({"rollno" : [20,21,22,30,24], "name" : ["kanishka",'umang',"naina","kunal","manu"]})
v2 = pd.DataFrame({"rollno" : [20,21,22,23,25], "name" : ["kanishka",'umang',"anjali","kunal","shipra"]})
std_info = pd.merge(v1,v2, left_index = True, right_index= True)
print(std_info)

   rollno_x    name_x  rollno_y    name_y
0        20  kanishka        20  kanishka
1        21     umang        21     umang
2        22     naina        22    anjali
3        30     kunal        23     kunal
4        24      manu        25    shipra

In [ ]:
import pandas as pd
v1 = pd.DataFrame({"rollno" : [20,21,22,23,24], "name" : ["kanishka",'umang',"naina","kunal","manu"]})
v2 = pd.DataFrame({"rollno" : [20,21,22,23,24], "marks" : [60,20,80,50,70]})
pd.merge(v1,v2, right_index = True, left_index = True, suffixes = ("9th", "10th"))

   rollno9th      name  rollno10th  marks
0         20  kanishka          20     60
1         21     umang          21     20
2         22     naina          22     80
3         23     kunal          23     50
4         24      manu          24     70

# **JOIN**

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A" : [2,3,4,5], "B" : ["a","b","c","d"]})
df2 = pd.DataFrame({"D" : [2,4,6,8], "C" : ["a", "c", "e","f"]})
df1.join(df2)

   A  B  D  C
0  2  a  2  a
1  3  b  4  c
2  4  c  6  e
3  5  d  8  f

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A" : [2,3,4,5], "B" : ["a","b","c","d"]}, index=["a", "b", "c","d"])
df2 = pd.DataFrame({"C" : [2,4,6,8], "D" : ["a", "c", "e","f"]})
df1.join(df2)

   A  B   C    D
a  2  a NaN  NaN
b  3  b NaN  NaN
c  4  c NaN  NaN
d  5  d NaN  NaN

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A" : [2,3,4,5], "B" : ["a","b","c","d"]}, index=[1,2,3,4])
df2 = pd.DataFrame({"C" : [2,4,6,8], "D" : ["a", "c", "e","f"]})
df2.join(df1)

   C  D    A    B
0  2  a  NaN  NaN
1  4  c  2.0    a
2  6  e  3.0    b
3  8  f  4.0    c

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A" : [10,20,30,40], "B" : ["a","b","c","d"]}, index=["a", "b", "c","d"])
df2 = pd.DataFrame({"C" : [20,30], "D" : ["a","c"]}, index = ["a", "b"])
df1.join(df2)

    A  B     C    D
a  10  a  20.0    a
b  20  b  30.0    c
c  30  c   NaN  NaN
d  40  d   NaN  NaN

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A" : [10,20,30,40], "B" : ["a","b","c","d"]}, index=["a", "b", "c","d"])
df2 = pd.DataFrame({"C" : [20,30], "D" : ["a","c"]}, index = ["a", "b"])
df2.join(df1)

    C  D   A  B
a  20  a  10  a
b  30  c  20  b

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A" : [10,20,30,40], "B" : ["a","b","c","d"]}, index=["a", "b", "c","d"])
df2 = pd.DataFrame({"C" : [20,30], "D" : ["a","c"]}, index = ["a", "b"])
df1.join(df2, how = "inner")

    A  B   C  D
a  10  a  20  a
b  20  b  30  c

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A" : [10,20,30,40], "B" : ["a","b","c","d"]}, index=["a", "b", "c","d"])
df2 = pd.DataFrame({"C" : [20,30], "D" : ["a","c"]}, index = ["a", "b"])
df1.join(df2, how = "outer")

    A  B     C    D
a  10  a  20.0    a
b  20  b  30.0    c
c  30  c   NaN  NaN
d  40  d   NaN  NaN

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A" : [10,20,30,40], "B" : ["a","b","c","d"]}, index=["a", "b", "c","d"])
df2 = pd.DataFrame({"C" : [20,30], "D" : ["a","c"]}, index = ["a", "b"])
df1.join(df2, how = "left")

    A  B     C    D
a  10  a  20.0    a
b  20  b  30.0    c
c  30  c   NaN  NaN
d  40  d   NaN  NaN

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A" : [10,20,30,40], "B" : ["a","b","c","d"]}, index=["a", "b", "c","d"])
df2 = pd.DataFrame({"C" : [20,30], "D" : ["a","c"]}, index = ["a", "b"])
df1.join(df2, how = "right")

    A  B   C  D
a  10  a  20  a
b  20  b  30  c

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A" : [10,20,30,40], "B" : ["a","b","c","d"]}, index=["a", "b", "c","d"])
df2 = pd.DataFrame({"A" : [20,30], "C" : ["a","c"]}, index = ["a", "b"])
df1.join(df2, how = "right", lsuffix = "_left")

   A_left  B   A  C
a      10  a  20  a
b      20  b  30  c

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A" : [10,20,30,40], "B" : ["a","b","c","d"]}, index=["a", "b", "c","d"])
df2 = pd.DataFrame({"A" : [20,30], "C" : ["a","c"]}, index = ["a", "b"])
df1.join(df2, how = "right", rsuffix = "_right")

    A  B  A_right  C
a  10  a       20  a
b  20  b       30  c

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A" : [10,20,30,40], "B" : ["a","b","c","d"]})
df2 = pd.DataFrame({"C" : [20,30,40,50], "D" : ["a","c","e","f"]})
df3 = pd.DataFrame({"E" : [20,30,40,50], "F" : ["a","c","e","f"]})
df1.join([df2,df3])

    A  B   C  D   E  F
0  10  a  20  a  20  a
1  20  b  30  c  30  c
2  30  c  40  e  40  e
3  40  d  50  f  50  f

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A" : [10,20,30,40], "B" : ["a","b","c","d"]})
df2 = pd.DataFrame({"C" : [20,30,40,50], "D" : ["a","c","e","f"]})
df3 = pd.DataFrame({"E" : [20,30,40,50], "F" : ["a","c","e","f"]})
df1.join(df2).join(df3)

    A  B   C  D   E  F
0  10  a  20  a  20  a
1  20  b  30  c  30  c
2  30  c  40  e  40  e
3  40  d  50  f  50  f

#**Concat**

In [ ]:
import pandas as pd
roll_no1 = pd.Series([1,2,3,4])
roll_no2 = pd.Series([10,20,30,40])
pd.concat([roll_no1, roll_no2])

0     1
1     2
2     3
3     4
0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
import pandas as pd
roll_no1 = pd.Series([1,2,3,4])
roll_no2 = pd.Series([10,20,30,40])
pd.concat([roll_no1, roll_no2], axis = 0)          #using axis = 1

0     1
1     2
2     3
3     4
0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
import pandas as pd
roll_no1 = pd.Series([1,2,3,4])
roll_no2 = pd.Series([10,20,30,40])
pd.concat([roll_no1, roll_no2], axis = 1)        #using axis = 1

   0   1
0  1  10
1  2  20
2  3  30
3  4  40

In [ ]:
import pandas as pd
roll_no1 = pd.Series([1,2,3,4])
roll_no2 = pd.Series([10,20,30,40])
pd.concat([roll_no1, roll_no2], axis = 0 , ignore_index = True)      #using ignore_index value true

0     1
1     2
2     3
3     4
4    10
5    20
6    30
7    40
dtype: int64

In [ ]:
import pandas as pd
roll_no1 = pd.Series([1,2,3,4])
roll_no2 = pd.Series([10,20,30,40])
pd.concat([roll_no1, roll_no2], axis = 0 , ignore_index = False)      #using ignore_index value false

0     1
1     2
2     3
3     4
0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
df1 = pd.DataFrame({"A" : [1,2,3], "B" : ["a", "b", "c"]})
df2 = pd.DataFrame({"A" : [1,2,3], "B" : ["a", "b", "c"]})
pd.concat([df1,df2])

   A  B
0  1  a
1  2  b
2  3  c
0  1  a
1  2  b
2  3  c

In [ ]:
df1 = pd.DataFrame({"A" : [1,2,3], "B" : ["a", "b", "c"]})
df2 = pd.DataFrame({"A" : [1,2,3], "B" : ["a", "b", "c"]})
pd.concat([df1,df2], axis = 1)

   A  B  A  B
0  1  a  1  a
1  2  b  2  b
2  3  c  3  c

Note : we can't use left and right but we can use inner and outer

In [ ]:
df1 = pd.DataFrame({"A" : [1,2,3], "B" : ["a", "b", "c"]})
df2 = pd.DataFrame({"A" : [1,2,3], "B" : ["a", "b", "c"]})
pd.concat([df1,df2], axis = 1, join="inner")

   A  B  A  B
0  1  a  1  a
1  2  b  2  b
2  3  c  3  c

In [ ]:
df1 = pd.DataFrame({"A" : [1,2,3], "B" : ["a", "b", "c"]})
df2 = pd.DataFrame({"A" : [1,2,3], "B" : ["a", "b", "c"]})
pd.concat([df1,df2], axis = 1, join="outer")

   A  B  A  B
0  1  a  1  a
1  2  b  2  b
2  3  c  3  c

In [ ]:
df1 = pd.DataFrame({"A" : [1,2,3], "B" : ["a", "b", "c"]})
df2 = pd.DataFrame({"A" : [1,2,3], "B" : ["a", "b", "c"]})
pd.concat([df1,df2], axis = 1, join="left")       #we cannot use left in concat

ValueError: Only can inner (intersect) or outer (union) join the other axis

In [ ]:
df1 = pd.DataFrame({"A" : [1,2,3], "B" : ["a", "b", "c"]})
df2 = pd.DataFrame({"A" : [1,2,3], "B" : ["a", "b", "c"]})
pd.concat([df1,df2], axis = 1, join="right")            #we cannot use right in concat

ValueError: Only can inner (intersect) or outer (union) join the other axis

In [ ]:
df1 = pd.DataFrame({"A" : [1,2,3], "B" : ["a", "b", "c"]})
df2 = pd.DataFrame({"" : [1,2,3], "B" : ["a", "b", "c"]})
pd.concat([df1,df2], axis = 1, keys=(["kanishka", "umang"]))

  kanishka    umang
         A  B        B
0        1  a     1  a
1        2  b     2  b
2        3  c     3  c

In [ ]:
df1 = pd.DataFrame({"A" : [1,2,3], "B" : ["a", "b", "c"]})
df2 = pd.DataFrame({"A" : [4,5,6], "B" : ["d", "e", "f"]})
pd.concat([df1,df2], axis = 0, keys=(["kanishka", "umang"]))

            A  B
kanishka 0  1  a
         1  2  b
         2  3  c
umang    0  4  d
         1  5  e
         2  6  f

In [ ]:
df1 = pd.DataFrame({"A" : [1,2,3]})
df2 = pd.DataFrame({"A" : [1,2,3], "B" : ["a", "b", "c"]})
pd.concat([df1,df2], axis = 1)

   A  A  B
0  1  1  a
1  2  2  b
2  3  3  c

In [ ]:
# Display the final number of rows and columns
print("Final Shape:")
print(california_housing_test_df.shape)

# Check remaining missing values
print("\nMissing Values:")
print(california_housing_test_df.isnull().sum())

# Check remaining duplicate rows
print("\nDuplicate Rows:")
print(california_housing_test_df.duplicated().sum())

# Display final data
print("\nFinal Dataset:")
print(california_housing_test_df.head())

   A  B    A    B
0  1  a  2.0    a
1  2  b  4.0    c
2  3  c  NaN  NaN

In [ ]:
# Import the pandas library for data manipulation
import pandas as pd

# Create the first DataFrame (df1)
df1 = pd.DataFrame({"A" : [2,3,4,5], "B" : ["a","b","c","d"]})

# Create the second DataFrame (df2)
df2 = pd.DataFrame({"A" : [2,4,6,8], "B" : ["a", "c", "e", "f"]})

# Perform a merge operation on df1 and df2.
# By default, pandas performs an inner merge on common columns (here, 'A' and 'B').
# It will return rows where the values in both 'A' and 'B' columns match in both DataFrames.
pd.merge(df1, df2)

In [ ]:
# Import the pandas library for data manipulation
import pandas as pd

# Create the first DataFrame (df1)
df1 = pd.DataFrame({"A" : [2,3,4,5], "B" : ["a","b","c","d"]})

# Create the second DataFrame (df2)
df2 = pd.DataFrame({"A" : [2,4,6,8], "B" : ["a", "c", "e", "f"]})

# Perform a merge operation on df1 and df2 without specifying 'on' or 'how'.
# By default, pandas performs an inner merge on common columns (here, 'A' and 'B').
# It will return rows where the values in both 'A' and 'B' columns match in both DataFrames.
print("Result of default merge (on 'A' and 'B'):")
print(pd.merge(df1, df2))

# Perform an inner merge specifically on column 'A'.
# This operation will join rows from df1 and df2 where the values in column 'A' are identical.
# Since there's also a common column 'B' but the merge is explicitly on 'A',
# pandas will rename the 'B' columns to 'B_x' (from df1) and 'B_y' (from df2) to avoid conflicts.
print("\nResult of inner merge on 'A':")
print(pd.merge(df1, df2 ,on= "A",how="inner"))