#Chapter 1
**Data Manipulation With Pandas**

#1.Series

1. Write a Python program using Pandas to create a Series from the given marks [2, 4, 6, 8, 10] and customize its index as a, b, c, d, e. Also display the type of the Series.

In [ ]:
import pandas as pd
marks = [2,4,6,8,10]
ds = pd.Series(marks)
print(type(ds))

<class 'pandas.core.series.Series'>

2. Write a Python program using Pandas to create a Series from the marks [2, 4, 6, 8, 10] and assign custom indexes ["a", "b", "c", "d", "e"]. Display the Series.

In [6]:
#customize index
import pandas as pd
marks = [2,4,6,8,10]
ds = pd.Series(marks, index = ["a","b","c","d","e"])
print(ds)

a     2
b     4
c     6
d     8
e    10
dtype: int64

3. Write a Python program using Pandas to create a Series from the marks [2, 4, 6, 8, 10] and assign custom indexes ["a", "b", "c", "d", "e"].

In [5]:
import pandas as pd
marks = [2,4,6,8,10]
ds = pd.Series(marks, index = ["a","b","c","d"])       #it will give error if the length is not same
print(ds)

ValueError: Length of values (5) does not match length of index (4)

4. Write a Python program using Pandas to create a Series from the marks [2, 4, 6, 8, 10] and assign custom indexes ["a", "b", "c", "d", "e"].

In [4]:
import pandas as pd
marks = [2,4,6,8,10]
ds = pd.Series(marks, index = ["a","b","c","d","e", "f"])        #it will give error if the length is not same
print(ds)

ValueError: Length of values (5) does not match length of index (6)

5. Write a Python program using Pandas to create a Series from the marks [2, 4, 6, 8, 10] with custom index labels ["a", "b", "c", "d", "e"], convert the data type to float, and assign a name to the Series. Then display the Series.

In [ ]:
import pandas as pd
marks = [2,4,6,8,10]
ds = pd.Series(marks, index = ["a","b","c","d","e"], dtype = "float")
print(ds)

a     2.0
b     4.0
c     6.0
d     8.0
e    10.0
dtype: float64

In [ ]:
import pandas as pd
marks = [2,4,6,8,10]
ds = pd.Series(marks, index = ["a","b","c","d","e"], dtype = "float", name = "marksheetrecord")    #also added file name
print(ds)

a     2.0
b     4.0
c     6.0
d     8.0
e    10.0
Name: marksheetrecord, dtype: float64

**1.1 common operations**

6. Write a Python program using Pandas to perform common operations on a Series and find its sum, minimum, maximum, and mean.

In [ ]:
print("sum no. of series",ds.sum())
print("min no. of series", ds.min())
print("max no. of series",ds.max())
print("mean no. of series",ds.mean())

sum no. of series 30.0
min no. of series 2.0
max no. of series 10.0
mean no. of series 6.0

**1.2 Index and Slicing**

7. Write a Python program using Pandas to access an element of a Series using its integer position.

In [7]:
print(f"acess element by int", {ds[1]})

acess element by int {np.int64(4)}

/tmp/ipykernel_798/4249669401.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"acess element by int", {ds[1]})

8. Write a Python program to access an element of a Pandas Series using its index label.

In [8]:
print(f"acess element by variable", {ds["a"]})

acess element by variable {np.int64(2)}

9. Write a Python program to perform slicing on a Pandas Series and display the first three elements.

In [ ]:
print("slicing in series", ds[0:3])

slicing in series a    2.0
b    4.0
c    6.0
Name: marksheetrecord, dtype: float64

**1.3 Vectorize Operations**

10. Write a Python program using Pandas to perform vectorized operations on a Series by multiplying all its elements by 3.

In [ ]:
ds *3

a     6.0
b    12.0
c    18.0
d    24.0
e    30.0
Name: marksheetrecord, dtype: float64

11. Write a Python program using Pandas to perform vectorized operations on a Series by adding all its elements by 2.

In [9]:
ds +2

a     4
b     6
c     8
d    10
e    12
dtype: int64

12. Write a Python program using Pandas to perform subtraction on all elements of a Series by subtracting 5 from each value.

In [ ]:
ds - 5

a   -3.0
b   -1.0
c    1.0
d    3.0
e    5.0
Name: marksheetrecord, dtype: float64

13. Write a Python program using Pandas to perform division on all elements of a Series

In [ ]:
ds/2

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: marksheetrecord, dtype: float64

14. Write a Python program using Pandas to perform exponentiation on a Series by raising each element to the power of 2.

In [ ]:
ds**2

a      4.0
b     16.0
c     36.0
d     64.0
e    100.0
Name: marksheetrecord, dtype: float64

15. Write a Python program using Pandas to find the remainder when each element of a Series is divided by 5.

In [ ]:
ds%5

a    2.0
b    4.0
c    1.0
d    3.0
e    0.0
Name: marksheetrecord, dtype: float64

16. Create a Pandas Series from a dictionary containing a student's name, age, and marks, and then access and display the student's name from the Series.

In [ ]:
info = {
    "name": "kanishka",
    "age" : 21,
    "marks": [20,30,40,50]
    }
ds1 = pd.Series(info)
ds1["name"]

'kanishka'

17. Create a Pandas Series with a single value 5 and display it.

In [ ]:
#create a diit with sinle number
num = pd.Series(5)
print(num)

0    5
dtype: int64

18. Create a Pandas Series with a single value 5 and assign the custom index labels [1, 2, 3, 4, 5]. Then display the Series.

In [ ]:
num = pd.Series(5, index = [1,2,3,4,5])
print(num)

1    5
2    5
3    5
4    5
5    5
dtype: int64

19. Create two Pandas Series with the same index [1, 2, 3, 4, 5], containing values 5 and 10, and add them together.

In [ ]:
num1 = pd.Series(5, index = [1,2,3,4,5])
num2 = pd.Series(10, index = [1,2,3,4,5])
print(num1 + num2)

1    15
2    15
3    15
4    15
5    15
dtype: int64

20. Create two Pandas Series with different index labels—[1,2,3,4,5] and ["a","b","c","d","e"]—and add them together. Observe the result when the indexes do not match.

In [ ]:
num1 = pd.Series(5, index = [1,2,3,4,5])
num2 = pd.Series(10, index = ["a","b","c","d","e"])
print(num1 + num2)

1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

#2. Data Frame

**2.1 Data Frame

21. Create a Pandas DataFrame using a dictionary containing students' names, roll numbers, and marks, and display the DataFrame.

In [ ]:
import pandas as pd
students = {
    "name" : ["kanishka", "umang", 'sadaf'],
    "roll_no." : [100, 101,102],
    "marks" : [80, 86, 88]
}
df = pd.DataFrame(students)
print(df)

       name  roll_no.  marks
0  kanishka       100     80
1     umang       101     86
2     sadaf       102     88

22. Create a Pandas DataFrame using a dictionary containing students' names, roll numbers, and marks, and display the DataFrame.

In [ ]:
#value error
import pandas as pd
students = {
    "name" : ["kanishka", "umang", 'sadaf'],
    "roll_no." : [100, 101],      #length of the value is not same
    "marks" : [80, 86, 88]
}
df = pd.DataFrame(students)
print(df)

ValueError: All arrays must be of the same length

23. Create a Pandas DataFrame using a list of lists, where the first list contains student names and the second list contains their marks. Display the DataFrame.

In [ ]:
#creating a dataframe with the help of list
stud_info = [["a","b", "c"], [20,40,60]]
pd.DataFrame(stud_info)
df #df without print

       name  roll_no.  marks
0  kanishka       100     80
1     umang       101     86
2     sadaf       102     88

24. Create a Pandas DataFrame using Pandas Series and display the DataFrame.

In [ ]:
#creating a dataframe with the help of list
stud_info = [["a","b", "c"], [20,40,60]]
pd.DataFrame(stud_info)
print(df) #df with print

       name  roll_no.  marks
0  kanishka       100     80
1     umang       101     86
2     sadaf       102     88

25. Create a Pandas DataFrame using two Pandas Series: one containing student names and the other containing their roll numbers. Then display the DataFrame.

In [ ]:
#create dataframe with the help series
sr = {
    "name" :pd.Series(["kanishka", "umang", "sadaf", "kunal", "naina"]),
    "roll_no." : pd.Series([10,11,12,13,15])
}
df = pd.DataFrame(sr)
df

       name  roll_no.
0  kanishka        10
1     umang        11
2     sadaf        12
3     kunal        13
4     naina        15

2.1 Arithmetic operations in DataFrame

26. Create a Pandas DataFrame with two columns a and b containing the given values, and display the DataFrame

In [ ]:
var = pd.DataFrame({'a':[1,2,3,4],'b':[5,6,7,8]})
var

   a  b
0  1  5
1  2  6
2  3  7
3  4  8

27. Create a Pandas DataFrame with columns a and b, then create a new column c by adding the values of columns a and b. Display the updated DataFrame.

In [11]:
var = pd.DataFrame({"a":[1,2,3,4],"b":[5,6,7,8]})
var['c']=var['a']+ var['b']
var

   a  b   c
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

2.2 Filtering

28. Create a DataFrame with columns a and b, calculate a new column c by adding them, and create a Boolean column python that checks whether c > 10.

In [ ]:
var = pd.DataFrame({'a':[1,2,3,4],'b':[5,6,7,8]})
var['c'] = var["a"] + var["b"]
var["python"] = var["c"] > 10
var

   a  b   c  python
0  1  5   6   False
1  2  6   8   False
2  3  7  10   False
3  4  8  12    True

29. Create a DataFrame with columns a and b, calculate column c as their sum, and create a Boolean column python that checks whether c >= 10.

In [ ]:
var = pd.DataFrame({'a':[1,2,3,4],'b':[5,6,7,8]})
var['c'] = var["a"] + var["b"]
var["python"] = var["c"] >= 10
var

   a  b   c  python
0  1  5   6   False
1  2  6   8   False
2  3  7  10    True
3  4  8  12    True

2.2 Handling Missing Values

30. Create a student DataFrame using a dictionary containing name, roll number, marks, subject, and city, with some missing values represented by np.nan, and display the DataFrame.

In [ ]:
import numpy as np
std = {
    "name" : ["kanishka", "umang", "sadaf", "kunal", "naina"],
    "roll_no." : [10,11,12,15, np.nan],
    "marks" : [20,np.nan,30, 40,50],
    "subject" : ["hindi", "english", np.nan,"maths", "physics"],
    "city": ["delhi", np.nan,"bijnor", "muzaffarnaar", "chandigarh"]
}
df

       name  roll_no.
0  kanishka        10
1     umang        11
2     sadaf        12
3     kunal        13
4     naina        15

31. Create a Pandas DataFrame containing student details with some missing values represented by np.nan. Then use df.info() to display the DataFrame’s column names, non-null counts, data types, and memory usage.

In [ ]:
import numpy as np
std = {
    "name" : ["kanishka", "umang", "sadaf", "kunal", "naina"],
    "roll_no." : [10,11,12,15, np.nan],
    "marks" : [20,np.nan,30, 40,50],
    "subject" : ["hindi", "english", np.nan,"maths", "physics"],
    "city": ["delhi", np.nan,"bijnor", "muzaffarnaar", "chandigarh"]
}
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      5 non-null      object
 1   roll_no.  5 non-null      int64
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

32. Create a student DataFrame containing missing values using np.nan, then use df.isnull().sum().sum() to find the total number of missing values in the DataFrame.

In [ ]:
import numpy as np
std = {
    "name" : ["kanishka", "umang", "sadaf", "kunal", "naina"],
    "roll_no." : [10,11,12,15, np.nan],
    "marks" : [20,np.nan,30, 40,50],
    "subject" : ["hindi", "english", np.nan,"maths", "physics"],
    "city": ["delhi", np.nan,"bijnor", "muzaffarnaar", "chandigarh"]
}
df.isnull().sum().sum()

np.int64(0)

33. Create a DataFrame containing missing (NaN) values and use the dropna() function to remove all rows that contain at least one missing value. Display the resulting DataFrame.

In [ ]:
import numpy as np
std = {
    "name" : ["kanishka", "umang", "sadaf", "kunal", "naina"],
    "roll_no." : [10,11,12,15, np.nan],
    "marks" : [20,np.nan,30, 40,50],
    "subject" : ["hindi", "english", np.nan,"maths", "physics"],
    "city": ["delhi", np.nan,"bijnor", "muzaffarnaar", "chandigarh"]
}
df.dropna()

       name  roll_no.  marks subject          city
0  kanishka      10.0   20.0   hindi         delhi
3     kunal      15.0   40.0   maths  muzaffarnaar

34. Create a Pandas DataFrame with missing values and use dropna(subset=["marks"]) to remove only those rows where the marks column contains a missing value. Display the resulting DataFrame.

In [ ]:
import numpy as np
import pandas as pd

std = {
    "name": ["kanishka", "umang", "sadaf", "kunal", "naina"],
    "roll_no.": [10, 11, 12, 15, np.nan],
    "marks": [20, np.nan, 30, 60, 50],
    "subject": ["hindi", "english", np.nan, "maths", "physics"],
    "city": ["delhi", np.nan, "bijnor", "muzaffarnaar", "chandigarh"],
}

df = pd.DataFrame(std)

# Drop rows where the 'marks' column has missing values
df = df.dropna(subset=["marks"])

print(df)

       name  roll_no.  marks  subject          city
0  kanishka      10.0   20.0    hindi         delhi
2     sadaf      12.0   30.0      NaN        bijnor
3     kunal      15.0   60.0    maths  muzaffarnaar
4     naina       NaN   50.0  physics    chandigarh